export enum FileLocation {
  OnlyLocal,
  OnlyRemote,
  Both,
}

export const iconFiletypeMap: { [key: string]: string } = {
  "3g2": "video-file",
  "3gp": "video-file",
  "amv": "video-file",
  "asf": "video-file",
  "avi": "video-file",
  "drc": "video-file",
  "flv": "video-file",
  "f4v": "video-file",
  "f4p": "video-file",
  "f4a": "video-file",
  "f4b": "video-file",
  "gifv": "video-file",
  "m4v": "video-file",
  "mkv": "video-file",
  "mng": "video-file",
  "mov": "video-file",
  "qt": "video-file",
  "mp4": "video-file",
  "m4p": "video-file",
  "mp2": "video-file",
  "mpg": "video-file",
  "mpeg": "video-file",
  "mpe": "video-file",
  "m2v": "video-file",
  "MTS": "video-file",
  "M2TS": "video-file",
  "TS": "video-file",
  "mxf": "video-file",
  "nsv": "video-file",
  "ogv": "video-file",
  "ogg": "video-file",
  "rm": "video-file",
  "rmvb": "video-file",
  "roq": "video-file",
  "svi": "video-file",
  "viv": "video-file",
  "vob": "video-file",
  "webm": "video-file",
  "wmv": "video-file",
  "yuv": "video-file",
  "jpg": "image-file",
  "jpeg": "image-file",
  "jpe": "image-file",
  "jif": "image-file",
  "jfif": "image-file",
  "jfi": "image-file",
  "png": "image-file",
  "gif": "image-file",
  "webp": "image-file",
  "tiff": "image-file",
  "tif": "image-file",
  "psd": "image-file",
  "bmp": "image-file",
  "jp2": "image-file",
  "svg": "image-file",
  "svgz": "image-file",
}